This is a notebook to demonstrate `numba` following this article:
https://pythonspeed.com/articles/numba-faster-python/

The example is a simple function which takes an array and calculates the monotonically increasing version:
```
[1, 2, 1, 3, 3, 5, 4, 6] → [1, 2, 2, 3, 3, 5, 5, 6]
```

In [1]:
import numpy as np
from numba import njit

In [2]:
# Defining a regular function
def monotonically_increasing(a):
     max_val = 0
     for i in range(len(a)):
         if a[i] > max_val:
             max_val = a[i]
         a[i] = max_val
     return a

In [3]:
# Defining the numba decorated function
@njit
def numba_monotonically_increasing(a):
     max_val = 0
     for i in range(len(a)):
         if a[i] > max_val:
             max_val = a[i]
         a[i] = max_val
     return a

In [4]:
# Let's check performance
# First run regular function:
%time monotonically_increasing(np.random.randint(0, 1000000, 1000000))

CPU times: user 166 ms, sys: 3.95 ms, total: 170 ms
Wall time: 169 ms


array([383172, 423888, 654019, ..., 999998, 999998, 999998])

In [5]:
# Second run regular function:
%time monotonically_increasing(np.random.randint(0, 1000000, 1000000))

CPU times: user 168 ms, sys: 4.04 ms, total: 172 ms
Wall time: 172 ms


array([668044, 912628, 927288, ..., 999998, 999998, 999998])

In [6]:
# Third run regular function:
%time monotonically_increasing(np.random.randint(0, 1000000, 1000000))

CPU times: user 164 ms, sys: 4.18 ms, total: 168 ms
Wall time: 167 ms


array([ 65725, 200677, 655033, ..., 999999, 999999, 999999])

Duration of execution is the same.

In [7]:
# First run numba function:
%time numba_monotonically_increasing(np.random.randint(0, 1000000, 1000000))

CPU times: user 520 ms, sys: 83.6 ms, total: 604 ms
Wall time: 281 ms


array([505355, 740026, 740026, ..., 999998, 999998, 999998])

In [8]:
# Second run numba function:
%time numba_monotonically_increasing(np.random.randint(0, 1000000, 1000000))

CPU times: user 6.37 ms, sys: 3.07 ms, total: 9.44 ms
Wall time: 8.07 ms


array([909981, 977894, 977894, ..., 999999, 999999, 999999])

In [9]:
# Third run numba function:
%time numba_monotonically_increasing(np.random.randint(0, 1000000, 1000000))

CPU times: user 6.67 ms, sys: 3.48 ms, total: 10.1 ms
Wall time: 8.1 ms


array([278903, 278903, 278903, ..., 999997, 999997, 999997])

First run is much slower (function is compiled) but subsequent runs are ~14 times faster!

Let's try time it to see the average time for many loops:

In [10]:
%timeit monotonically_increasing(np.random.randint(0, 1000000, 1000000))

162 ms ± 1.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
%timeit numba_monotonically_increasing(np.random.randint(0, 1000000, 1000000))

4.36 ms ± 14 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Woah!

In [13]:
162/4.4

36.81818181818181

37 times faster!!!